#to run: java hw09.MultithreadedServer
#	javac -sourcepath ./hw09/  ./hw09/test/my_tests.java 
#javac  -sourcepath ./hw09/ ./hw09/MultithreadedServer.java
#/usr/share/java/
all:
	javac  -sourcepath ./hw09/ ./hw09/MultithreadedServer.java
cu:
	javac  -sourcepath ./hw09/. ./hw09/MultithreadedServer.java ./hw09/constants.java ./hw09/Account.java	
	javac -sourcepath ./hw09/  ./hw09/test/my_tests.java 

clean:
	rm ./hw09/*.class
	rm ./hw09/test/*.class
